:relative-path: ../../
include::{docdir}/variables.adoc[]

Once your have your application ready (see <<quick-start.adoc#, Quick start>> if you don't have created an application) you can:

* Run the backend code (Worker) locally
* Deploy your application

To do this we provide a _CLI_ (Command Line Interface) to help you focus on your code and not spend time on writing commands or scripts.

The _CLI_ module is declared in the `package.json` of the project so it is installed by npm when you create your project
(see <<quick-start.adoc#_create_your_first_application, how to create an application using npm>> if you haven't created a project). 

When the project is created, we configure the `package.json` with a `scripts` section to make aliases that work
directly with npm.

== Use npm script aliases to run the _CLI_

[source,console,subs="attributes+"]
----
$ npm run <alias>
----

If you want to run your worker locally using script alias, you can execute:

[source,console,subs="attributes+"]
----
$ npm run start
----

[TIP]
====
The `start` alias calls `zeta run` under the hood.

The `start` alias is used because it is the standard alias to use in development. 
We follow npm conventions so a user that is used to npm know which command to
execute to start is project locally.
====


If you want to deploy your application using script alias, you can execute:

[source,console,subs="attributes+"]
----
$ npm run deploy
----

[TIP]
====
The `start` alias calls `zeta push` under the hood.
====

== Use _CLI_ directly


With the CLI, you can run your worker with:

.Run worker
[source, console, linenums]
----
$ zeta run
----

Or deploy your application with:

.Deploy the application
[source, console, linenums]
----
$ zeta push
----

There are 3 ways to use directly `zeta` commands provided by the _CLI_:

- Set an environment variable that points to your local `node_modules/.bin` (recommended)
- Use `npx` tool
- Install _CLI_ as global (not recommended)

=== Update your PATH environment variable (recommended)

In order to be able to run `zeta` commands directly, you need to update your PATH.

[role=tab-container]
Update environement variables


[role=tab]
Debian/Ubuntu/MacOSX

You need to add it to your shell config file ~/.zshrc ~/.profile or ~/.bashrc.

[source,console,subs="attributes+"]
----
$ export PATH=./node_modules/.bin:$PATH
----

Note that this will not automatically update your path for the remainder of the session. To do this, you should run:

[source,console,subs="attributes+"]
----
$ source ~/.zshrc
$ source ~/.profile
$ source ~/.bashrc
----

[role=tab]
Windows 10 and Windows 8

- In Search, search for and then select: System (Control Panel)
- Click the Advanced system settings link.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run zeta command.

[role=tab]
Windows 7

- From the desktop, right click the Computer icon.
- Choose Properties from the context menu.
- Click the Advanced system settings link.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run zeta command.

[role=tab]
Windows Vista

- From the desktop, right click the My Computer icon.
- Choose Properties from the context menu.
- Click the Advanced tab (Advanced system settings link in Vista).
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run zeta command.


[role=tab]
Windows XP

- Select Start, select Control Panel. double click System, and select the Advanced tab.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run zeta command.

[role=tab-container-end]
-

=== Use npx tool

npx is shipped with npm standard install

[source,console,subs="attributes+"]
----
$ npx zeta <command>
----

=== Install @zetapush/cli as a global command (not recommended)

[source,console,subs="attributes+"]
----
$ npm i -g @zetapush/cli
----

