:relative-path: ../../
include::{docdir}/variables.adoc[]

Once your have your application ready you can:

* Run the backend code (Worker) locally
* Deploy your application

To do this you need to use the _CLI_. To install it, launch:

== Update your PATH environement variable (recommended)

[role=tab-container]
Update environement variables


[role=tab]
Debian/Ubuntu/MacOSX

You need to add it to your shell config file ~/.zshrc ~/.profile or ~/.bashrc.

[source,console,subs="attributes+"]
----
$ export PATH=./node_modules/.bin:$PATH
----

Note that this will not automatically update your path for the remainder of the session. To do this, you should run:

[source,console,subs="attributes+"]
----
$ source ~/.zshrc 
$ source ~/.profile 
$ source ~/.bashrc 
----

[role=tab]
Windows

Windows 10 and Windows 8

- In Search, search for and then select: System (Control Panel)
- Click the Advanced system settings link.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run your java code.

Windows 7

- From the desktop, right click the Computer icon.
- Choose Properties from the context menu.
- Click the Advanced system settings link.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run your java code.

Windows Vista

- From the desktop, right click the My Computer icon.
- Choose Properties from the context menu.
- Click the Advanced tab (Advanced system settings link in Vista).
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run your java code.

Windows XP

- Select Start, select Control Panel. double click System, and select the Advanced tab.
- Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
- In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
- Reopen Command prompt window, and run your java code.

[role=tab-container-end]
-

== Use aliases command npm run <command>

[source,console,subs="attributes+"]
----
$ npm run start
----

== Use npx tool

npx is shipped with npm standard install

[source,console,subs="attributes+"]
----
$ npx zeta <command>
----

== Install @zetapush/cli as a global command (not recommended)

[source,console,subs="attributes+"]
----
$ npm i -g @angular/cli
----

With the CLI, you can run your worker with:

.Run worker
[source, console, linenums]
----
$ zeta run
----

Or deploy your application with:

.Deploy the application
[source, console, linenums]
----
$ zeta push
----
