:relative-path: ../../
include::{docdir}/variables.adoc[]


When you _deploy_ your application on the ZetaPush cloud, 
actually your application is split in two parts:

* The worker that contains your _custom cloud services_
* The static files for the front end

== Worker

When you deploy the worker (_custom cloud services_) of your application, we take care of the hosting of your code. 
In addition we manage the redundancy, the load-balancing, 
the high availability and the automatic scability of your _custom cloud services_.

A worker may also provide HTTP endpoints in addition to bidirectionnal connection provided as-is by ZetaPush.
If so, once published on the ZetaPush cloud, the HTTP url is displayed in your terminal.

[NOTE]
====
URLs to access your worker in HTTP(s) are also available in the link:{web-console-url}[ZetaPush web console^].
====

== Front end

For the front end part, the ZetaPush cloud hosts your application.
ZetaPush also manages redundancy of the static files in order to ensure
the high availability of you front end application.

The URL to access to your application is displayed in your terminal.

[NOTE]
====
URLs to access your front end are also available in the link:{web-console-url}[ZetaPush web console^].
====