:relative-path: ../../
include::{docdir}/variables.adoc[]

.Custom Cloud Service in development phase
[plantuml, custom-cloud-service-dev, png, role="center"]     
....
skinparam component {
	ArrowFontName Impact
    ArrowFontColor Black
    ArrowFontSize 14
}

node "Your computer" as local {
   rectangle "worker" {
        node "custom cloud service 1" as customCloudService1
        node "custom cloud service 2" as customCloudService2
   }

   rectangle "front" {
        node "client" as front1
   }
}

cloud "                                                                            ZetaPush Cloud" as zp {
    queue "bidirectional connection" as connection

    rectangle "cloud services" {
        node "cloud service 1" as cloudService1
        node "cloud service 2" as cloudService2
        node "cloud service 3" as cloudService3
    }
}

front1 <..> connection
customCloudService1 <..> connection
customCloudService2 <..> connection
cloudService1 <.up.> connection
cloudService2 <.up.> connection
cloudService3 <.up.> connection
....

Both front and worker are running locally. The front interacts with _custom cloud services_ contained in the worker through
ZetaPush Cloud.
As ZetaPush Cloud provides bidirectional connection, the _custom cloud services_ can also interact with the front through
ZetaPush Cloud too.

A _custom cloud service_ can interact with _built-in cloud services_ provided by ZetaPush.

[NOTE]
====
When you start using ZetaPush, you only develop locally so from your point of vue,
your front seems to directly interact with your _custom cloud services_.

In fact, all messages go through the Internet and ZetaPush Cloud.
It means that a published front can interact with a worker that is running locally and vice versa.

See <<reference.adoc#mix_local_and_remote, how to mix local worker with worker running in cloud>>
====





