:relative-path: ../
include::{docdir}/variables.adoc[]

You can generate a classic application with the following command :

.Generate application
[source, console]
----
$ npm init @zetapush myApp <1>
----
<1> _myApp_ is the name of the folder that will be created and will contain all generated files

[WARNING]
====
This command works only with npm >= 6.

**Using npm lower than 6**

include::{docdir}/common/init/init-npm-minor-6.adoc[leveloffset=+1]
====

This command can takes several parameters : 

* *--developer-login* : Define which developer login (ZetaPush account) to use
* *--developer-password* : Define which developer password (ZetaPush account) to use
* *--appName* : Define which application (defined in your ZetaPush account) to use

This will generate a tree structure of a classic application :

include::{docdir}/common/code/generated-tree-init.adoc[leveloffset=+1]

include::{docdir}/common/code/table-definition-generated-files.adoc[leveloffset=+1]

////
TODO: ailleurs
All dependencies are already installed, so you can run your application locally or deploy it. Npm scripts are also configured in the `package.json` file.

So you can use either the _CLI_ using the commands: 

- `zeta run` to start your custom cloud services locally
- `zeta push` to upload your code on ZetaPush cloud and let ZetaPush publish your application

Or run commands through npm:

- `npm run start` to start your custom cloud services locally
- `npm run deploy` to upload your code on ZetaPush cloud and let ZetaPush publish your application
////
