:relative-path: ../
include::{docdir}/variables.adoc[]

You can generate a classic application with the following command :

.Generate application
[source, console]
----
$ npm init @zetapush myApp <1>
----
<1> _myApp_ is the name of my generated application

WARNING: This command works only with npm >= 6. Otherwise, read this link:#_using_npm_lower_than_6[section].

This command can takes many parameters : 

* *--developer-login* : Define which developer login (ZetaPush account) use
* *--developer-password* : Define which developer password (ZetaPush account) use
* *--appName* : Define which application use

This will generate a tree structure of a classic application :

include::{docdir}/common/code/generated-tree-init.adoc[leveloffset=+1]

All dependencies are already installed, so you can run your application locally or deploy it.

To do this you can use the _CLI_ using the commands : `zeta run` and `zeta push`. 

TIP: To install the CLI you can launch : `npm install -g @zetapush/cli`.

The CLI dependency is already installed and npm scripts are created. So you can execute your code with `npm run start` and deploy your application with `npm run deploy`.

include::{docdir}/common/code/table-definition-generated-files.adoc[leveloffset=+1]

== Using npm lower than 6
include::{docdir}/common/init/init-npm-minor-6.adoc[leveloffset=+1]
