:relative-path: ./
include::{docdir}/variables.adoc[]

:appName: hello-world

////

Objectifs : apprendre à utiliser ZetaPush, comprendre les concepts et gagner du temps sur mon dev

== Requirements

X si déjà installé, on peut passer la section

=== System requirements

X installation

=== Using CLI

X ok

== ZetaPush concepts

Objectif : faire comprendre et utiliser les concepts fondamentaux de ZetaPush

X compte
  X expliquer qu'on doit avoir un compte
  X expliquer comment obtenir un compte (formulaire de demande)
  X expliquer que dans le futur, on pourra créer un compte soi-même
X organisation
X application
X env (futur)

== Develop your front with ZetaPush

Objectif : dire que ZetaPush fourni des services prêts à l'usage qui pourront à l'avenir être consommé directement.

X liste des services dispos
X requirements

X enlever la partie consommer un custom cloud service

== Develop your business logic

Objectif : accompagner le développeur à comprendre comment écrire son code métier rapidement et l'utiliser depuis son front

X définition
X coder un cloud service simple
  X define a custom cloud service
    X note pour dire qu'on peut créer plusieurs cloud services dans le même worker (+ namespace)
  X expose a custom cloud service
    X note pour dire qu'on peut exposer plusieurs cloud services
  X use your custom cloud service in your front
    X note pour dire qu'on peut faire autre chose que du web ?
  X run a custom cloud service
    X note pour lancer que le cloud service
  X compose cloud services
    X dependency injection
      X note pour aller voir plus en profondeur dans le fonctionnement de l'injection de dépendance
    X use built-in cloud service
      -> note pour voir comment configurer les cloud services
    X use another custom cloud service
      X note pour dire qu'on peut créer un module réutilisable
      X note pour distinguer qu'on peut avoir des clouds services privés et d'autres exposés

- develop fast
  - hot reload
    -> montrer comment gagner du temps
  - logs
    -> montrer comment logguer pour gagner du temps d'analyse
  - debug
    -> montrer comment débugger rapidement du code
  - testing ?
    -> montrer comment les tests peuvent faire gagner du temps

== Deploy/publish your application

Objectif : montrer comment déployer une application complète (front + worker)

indiquer qu'on peut redéployer à n'importe quel moment

.How to have initialization code
[NOTE]
====
A _custom cloud service_ may have initialization code to configure and prepare your application.

As said before, once published in the ZetaPush cloud, ZetaPush handles scalability and
high availability. So several worker instances will run in the same time and ZetaPush will
load-balance traffic between worker instances. In order to ensure only one ...
====


-> retirer parties avec déploiement partiel et mettre des liens à la place

== User management in your application

Objectif : montrer comment rapidement obtenir une gestion des utilisateurs pour se concentrer sur le code utile

- import user-management module
- configure for your needs
  -> note pour configuration avancée
  -> note pour adaptation (utiliser implementations custom)
- write your front to consume it
- test it locally
- test it remotely

== Store data in your application

Objectif : montrer comment rapidement stocker, lister, rechercher des données pour se concentrer sur le code utile

futur

== Secure your application

Objectif : montrer comment rapidement isoler, bloquer et filtrer l'accès à des fonctions/données

futur

////

= Developer manual

== Requirements

[NOTE]
====
If you already prepared your environment, you can skip this section.
====

=== System requirements

include::{docdir}/common/prerequisites/prerequisites.adoc[leveloffset=+1]

=== Using CLI

include::{docdir}/common/manual-initialization/use-manual-application.adoc[leveloffset=+2]

== ZetaPush concepts


In order to be able to use ZetaPush, you need a *ZetaPush account*. Your account is used when
you develop to run your project locally or to deploy it on ZetaPush cloud.

The code you produce is bound to an *application*.

An account belongs to an *organization*. An organization is useful to work in team.
You can have several applications for your organization.
You can manage access rights on applications according to members of your team.

As usual in development, you may need to run your application in different contexts (dev, continuous integration, 
prod...).
Each application may have several *environments*.
You can also manage access rights on environments according to members of your team.

[TIP]
====
Learn how to <<reference.adoc#add_application, add an application to your organization>>.

Learn how to <<reference.adoc#add_environment, add an environment to your application>>.

Learn how to <<reference.adoc#access_control_per_application, control access for an application>>.

Learn how to <<reference.adoc#access_control_per_environment, control access for a particular environment>>.
====

[IMPORTANT]
====
For now, environments are not fully supported but this feature will be available soon.
====


=== Create your account
include::{docdir}/common/manage/create-account.adoc[leveloffset=+2]



== Develop your front with ZetaPush

You may want to quickly provide a web application by just focusing on the visible part and the user experience
instead of wasting time on technical concerns.

ZetaPush provides built-in _cloud services_ to increase your productivity:

include::{docdir}/common/cloud-services/summary.adoc[leveloffset=+3]


ZetaPush cloud services need to be "created" before being able to use them. This way, you
can choose which services are part of your application instead of having them all.

[IMPORTANT]
====
Currently, using a front to interact with ZetaPush cloud services directly is not really possible due to
this "creation" phase. For security reasons, service creation and configuration can't be done via
a client. 

When the web console will be fully ready, ZetaPush cloud services "creation" will be
available through the web console.

Hopefully, you can use a worker to declare the use of a ZetaPush cloud service and even configure it. The
"creation" process is automatically handled by the worker.

See the next section to know how to develop _custom cloud services_ and use _ZetaPush cloud services_.
====

////
=== Requirements
include::{docdir}/common/usage-service/requirement-use-service.adoc[leveloffset=+3]


=== Use _cloud services_

==== Use a ZetaPush _cloud service_

Here we show how to create a worker that use the ZetaPush cloud service named `Stack`.


include::{docdir}/common/code/example-use-cloud-service-in-custom.adoc[]

[TIP]
====
`Stack` cloud service "creation" is automatically handled thanks to dependency injection.
ZetaPush detects that you need a ZetaPush service and prepare it.
so you focus your code on the usage of the service
not on its creation, you just ask for it.
====

include::{docdir}/common/code/example-call-stack-cloud-service-from-front.adoc[]


IMPORTANT: When you call a _cloud function_ from the client, the result is always a Promise even if the _custom cloud function_ is synchronous
because everything goes through the network.


==== Use a custom _cloud service_
include::{docdir}/common/usage-service/utilization-service.adoc[leveloffset=+3]


=== Configure/adapt ZetaPush cloud services

[TODO]
====
This section will describe how to configure a ZetaPush cloud service.
The configuration will be possible either through console or through worker.

https://github.com/zetapush/documentation/issues/51
====

=== Run your front locally

[TODO]
====
As described above, currently running only a front is not possible.
You need to have a least worker to create and configure ZetaPush services.

This section will be later described when this feature will be supported.
https://github.com/zetapush/documentation/issues/52
====
////



== Develop your business logic

Even if ZetaPush provides ready to use cloud services, we know that any application needs some
specific behaviors. Instead of limiting your possibilities, we provide a way to help you develop
quickly your own business logic.

=== What is a _custom cloud service_
include::{docdir}/common/custom-cloud-service/presentation-custom-cloud-service.adoc[leveloffset=+2]

=== Develop a _custom cloud services_

==== Define a _custom cloud service_
include::{docdir}/common/custom-cloud-service/create-custom-cloud-service.adoc[leveloffset=+3]

==== Expose a _custom cloud service_
include::{docdir}/common/custom-cloud-service/expose-custom-cloud-service.adoc[leveloffset=+3]

==== Use a _custom cloud service_ in your front
include::{docdir}/common/usage-service/utilization-service.adoc[leveloffset=+3]

==== Run application
include::{docdir}/common/usage-service/run-application.adoc[leveloffset=+3]

==== Compose cloud services

You can compose _cloud services_ either by using _built-in cloud services_ provided by ZetaPush or 
by using another of your _custom cloud services_.

===== Dependency injection
include::{docdir}/common/custom-cloud-service/dependencies-include-services.adoc[leveloffset=+3]

===== Use built-in _cloud service_
include::{docdir}/common/custom-cloud-service/use-cloud-services-in-custom.adoc[leveloffset=+3]

===== Use another _custom cloud service_
include::{docdir}/common/custom-cloud-service/use-custom-cloud-services-in-custom.adoc[leveloffset=+3]

=== Develop fast

==== Hot reload

TODO: https://github.com/zetapush/documentation/issues/53

==== Log from a _custom cloud service_

==== Debug a _custom cloud service_

==== Test a _custom cloud service_

== Deploy/publish your application

Once you have developed your application and tested it, you may want to deploy it on the ZetaPush cloud.

=== What will be deployed ?

include::{docdir}/common/deploy/what-is-deployment.adoc[leveloffset=+2]

==== Applications and environments

TODO: https://github.com/zetapush/documentation/issues/54


=== Deploy both front and _custom cloud services_ on the ZetaPush Cloud
include::{docdir}/common/deploy/how-to-deploy-app.adoc[leveloffset=+2]

=== Deploy your front on the ZetaPush Cloud
include::{docdir}/common/deploy/how-to-deploy-front.adoc[leveloffset=+2]

=== Deploy your _custom cloud services_ on the ZetaPush Cloud
include::{docdir}/common/deploy/how-to-deploy-worker.adoc[leveloffset=+2]

== User management in your application

== Store data in your application

== Secure your application

////
== Debug

=== Debug your application with VSCode
include::{docdir}/common/debug/how-to-debug-with-vscode.adoc[leveloffset=+2]

=== Debug your application with IntelliJ based IDE
include::{docdir}/common/debug/how-to-debug-with-webstorm.adoc[leveloffset=+2]

== Testing

TODO: https://github.com/zetapush/documentation/issues/55

=== Unit testing your front

TODO: https://github.com/zetapush/documentation/issues/56

=== Unit testing your custom cloud services

TODO: https://github.com/zetapush/documentation/issues/57

=== Integration testing your front

TODO: https://github.com/zetapush/documentation/issues/58

=== Integration testing your custom cloud services

TODO: https://github.com/zetapush/documentation/issues/59

=== Functional testing / end-to-end testing

TODO: https://github.com/zetapush/documentation/issues/60

// CONFIGURATION OF CLOUD SERVICES
== Configuration of cloud services

[#configuration-of-standard-user-workflow]
=== Standard User Workflow
include::{docdir}/common/cloud-services/standard-user-workflow/configuration.adoc[leveloffset=+2]

// EXTENSION OF CLOUD SERVICES
== Extension of cloud services

[#extension-of-standard-user-workflow]
=== Standard User Workflow
include::{docdir}/common/cloud-services/standard-user-workflow/extension.adoc[leveloffset=+2]
////