:relative-path: ./
include::{docdir}/variables.adoc[]

= Introduction

== ZetaPush Celtia

ZetaPush accelerates the creation of connected applications by providing turnkey services. The developer consumes the services needed to run his application using development kits ready to be integrated into his front end code.

ZetaPush Celtia represents a major version of ZetaPush with a major change: the developer can write business code in languages such as JavaScript and TypeScript.

The developer will focus on his business code and ZetaPush will make his life easier by providing him with all the common components such as user management, data storage, etc.

In addition, ZetaPush hosts business code and front-end code.

== Sections

[cols="5*^", role="sections-shortcut"]
|===
| <<quick-start.adoc#_quick_start, Quick Start>>
| <<tutorials.adoc#_tutorials, Tutorials>>
| <<how-to.adoc#_guides, Guides>>
| <<developer-manual.adoc#_developer_manual, Developer Manual>>
| <<reference.adoc#_reference, Reference>>

| If you want to start using ZetaPush quickly
| If you want to learn how to use ZetaPush Celtia main features, you can begin here
| If you want to go into some topics in depth
| If you want to cover completely each topic
| If you want to search for a particular piece of information
|===

// VOCABULARY
include::{docdir}/common/vocabulary/vocabulary.adoc[]
