:relative-path: ../../
include::{docdir}/variables.adoc[]

== Notif

Notification User API

User API for notifications.
For notifications to work properly, it is imperative that the resource name of a device remain constant over time.


=== send

Sends a native push notification to the target.

.send(parameters: <<common/cloud-services-types/notification-message.adoc#,NotificationMessage>>): Promise<<<common/cloud-services-types/notification-send-status.adoc#,NotificationSendStatus>>>

[source,typescript,linenums]
----
const response = await this.notif.send(parameters);
----

=== unregister

Unregisters the device for the current user and resource.
This verb does not need any parameters.

.unregister(parameters: <<common/cloud-services-types/.adoc#,undefined>>): Promise<<<common/cloud-services-types/void.adoc#,void>>>

[source,typescript,linenums]
----
const response = await this.notif.unregister(parameters);
----

=== register

Registers the device for the current user and resource.
This service maintains a mapping of __userkey/__resource to device registration IDs.
You MUST NOT re-use the same resource name from one device to another if you want to target specific devices with 'send'.
Only one registration can be active for a given __userKey/__resource pair in a notification service.
Device registration can be <b>neither impersonated nor called indirectly</b> (from a scheduled job).

.register(parameters: <<common/cloud-services-types/notifiable-device-registration.adoc#,NotifiableDeviceRegistration>>): Promise<<<common/cloud-services-types/void.adoc#,void>>>

[source,typescript,linenums]
----
const response = await this.notif.register(parameters);
----


=== How to use it ?

.worker/index.ts
[source,typescript,linenums]
----
import { Injectable } from '@zetapush/core';
import { Notif, NotificationMessage } from '@zetapush/platform-legacy'; <1>

@Injectable()
export default class Api {
  constructor(
    private notif: Notif <2>
  ) {}
  async doStuff(parameters: NotificationMessage) {
    const response = await this.notif.send(parameters); <3>
    return response;
  }
}
----
<1> Import `Notif` from platform
<2> Declare injected service
<3> Call injected service
