:relative-path: ../../
include::{docdir}/variables.adoc[]

As a reminder worker is the ZetaPush container that will handle your code that defines _custom cloud services_.
By convention, the code of your _custom cloud services_ is placed in files under `worker` directory:

.Tree structure convention
[source, console, subs="attributes,quotes"]
----
{appName}
├── _.zetarc_
├── _.gitignore_
├── _front_
│   ├── ...
│   └── ...
├── *worker*
│   ├── file1.ts
│   ├── file2.ts
│   ├── ...
│   ├── fileN.ts
│   └── index.ts
├── _package.json_
├── _README.md_
└── _tsconfig.json_
----

.Change directory structure
[TIP]
====
See more information about <<reference.adoc#different_directory_structures, directory structure convention and how to adapt the structure>>.
====


Translated into code, a _custom cloud service_ is just a `class` and its `methods` are the  _cloud functions_. 
The code is written in any `ts` file defined in `worker` directory. For small application like a "hello world",
write your code directly in `index.ts` file.
So the most basic example of a _custom cloud service_ is below:

include::{docdir}/common/code/basic-custom-cloud-service.adoc[leveloffset=+1]

.Change entry point
[TIP]
====
By default, the code above is directly written in `index.ts` file. This is done in order
to follow NodeJS conventions. Indeed, `index.ts` is the usually the file that imports
all other files.

You can write code of your _custom cloud services_ in any other file named as you want.
You will see later how to indicate to ZetaPush worker how to find your files if you don't
want to follow convention.
====

include::{docdir}/common/custom-cloud-service/define-cloud-function.adoc[leveloffset=+1]

.Define several _custom cloud services_
[TIP]
====
Obviously when your application grows, you need to split your _custom cloud service_ into several classes in order
to make your API more understandable and more maintainable.

You can learn <<reference.adoc#several_custom_cloud services, how to define several _custom cloud services_>>.
====


You have now a _custom cloud service_ that provides two _cloud functions_.
But until it is exposed, it can't be called from outside of the worker.

The next section describes how you can expose your _custom cloud service_.