:relative-path: ../../
include::{docdir}/variables.adoc[]

As a reminder worker is the ZetaPush container that will handle your code that defines _custom cloud services_.
By convention, the code of your _custom cloud services_ is placed in files under `worker` directory:

.Tree structure convention
[source, console, subs="attributes,quotes"]
----
{appName}
├── _.zetarc_
├── _.gitignore_
├── _front_
│   ├── ...
│   └── ...
├── *worker*
│   ├── file1.ts
│   ├── file2.ts
│   ├── ...
│   ├── fileN.ts
│   └── index.ts
├── _package.json_
├── _README.md_
└── _tsconfig.json_
----

.Change directory structure
[TIP]
====
See more information about <<reference.adoc#different_directory_structures, directory structure convention and how to adapt the structure>>.
====


Translated into code, a _custom cloud service_ is just a `class` and its `methods` are the  _cloud functions_. 
The code is written in any `ts` file defined in `worker` directory. For small application like a "hello world",
write your code directly in `index.ts` file.
So the most basic example of a _custom cloud service_ is below:

include::{docdir}/common/code/basic-custom-cloud-service.adoc[leveloffset=+1]

.Change entry point
[TIP]
====
By default, the code above is directly written in `index.ts` file. This is done in order
to follow NodeJS conventions. Indeed, `index.ts` is the usually the file that imports
all other files.

You can write code of your _custom cloud services_ in any other file named as you want.
You will see <<reference#change-worker-entry-point, in the reference part>> how to indicate to ZetaPush worker how to find your files if you don't
want to follow convention.
====

== Define a _cloud function_

Each _cloud function_ in a _custom cloud service_ is a standard JavaScript/TypeScript
method.
For example, if you want a _cloud function_ that receives two parameters you write:

.A more realistic _cloud function_
[source, javascript, linenums, role="highlight-lines:8-14"]
----
class HelloWorldAsCustomCloudService {                            // <1>
    constructor() {}                       

    helloWorld() {                         
        return "Hello World";
    }

    saySomething(message: string, times: number) {                // <2>
        let fullMessage = '';
        for(let i=0 ; i<times ; i++) {                            // <3>
            fullMessage += `${message}\n`
        }
        return fullMessage                                        // <4>
    }
}
----
<1> The _custom cloud service_ definition as seen before
<2> Declaration of a _cloud function_ named `saySomething`. This _cloud function_ accepts
two parameters. As <<reference.adoc#javascript_vs_typescript, TypeScript is the recommended way>>, each parameter is typed.
<3> Just for an example, the business logic consists in looping a number of times 
and concatenating the message. You can obviously write any code you want here.
<4> The _custom cloud function_ simply returns the contactenated string. 

.Why typing ?
[TIP]
====
Typing is optional but recommended to have a well defined API. Thanks to typing,
ZetaPush is able to generate more accurate <<reference.adoc#generate_api_documentation, documentation based on your code>> and also
<<reference.adoc#generate_sdks, generate mobile/web/IoT SDKs>> from your code with the right types so it
makes developing your clients easier (for example, auto-completion can be used).
====

.Tips about cloud functions
[TIP]
====
A _custom cloud service_ can have as many _custom cloud functions_ as you want.

A _custom cloud function_ can have as many parameters as you want. Parameters can be anything: `string`, `number`,
`boolean`, `array` or `object`. You can code your function as you always do.

A _custom cloud function_ can return anything including a link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]. 
You can also write your code using link:https://javascript.info/async-await[async/await syntax].
====

.Define several _custom cloud services_
[TIP]
====
Obviously when your application grows, you need to split your _custom cloud service_ into several classes in order
to make your API more understandable and more maintainable.

You can learn <<reference.adoc#several_custom_cloud services, how to define several _custom cloud services_>>.
====


You have now a _custom cloud service_ that provides two _cloud functions_.
But until it is exposed, it can't be called from outside of the worker.

The next section describes how you can expose your _custom cloud service_.