:relative-path: ../
include::{docdir}/variables.adoc[]

First of all, if you want to include some services (custom or not), you need to use _dependencies injection_ of ZetaPush. All your dependencies injection will be facilitated.

So, you need to import the package `@zetapush/platform` to import `Inject()` that will inject the dependencies, as its name suggests.

.Install @zetapush/platform
[source, console, linenums]
----
$ npm install --save @zetapush/platform
----

NOTE: The dependencies injection of ZetaPush use the library *injection-js* 

For example, to import an other service in your own, you simply need to write :

.Import service
[source, javascript, linenums, role="highlight-lines:6-11,13"]
----
const { Inject, Stack } = require('@zetapush/platform'); <1>
const MyOtherService = require('./services.js'); <2>

class MyOwnService {

    static get parameters() { <3>
        return [
            new Inject(MyOtherService),
            new Inject(Stack)
        ]
    }

    constructor(myOtherService, stack) { <4>
        ...
    }
}
----
<1> We import the `Inject` object and a service (_Stack_) provided by ZetaPush
<2> One other service we want to import
<3> We create a static method to implement our dependencies injection (_injection-js_ syntax)
<4> We use instances of our injected services in our service throught the constructor

TIP: The order in your `parameters` method need to be the same in your constructor. (Here, first _MyOtherService_, then _Stack_)

NOTE: Import and use a _cloud service_ provided by ZetaPush or a _custom cloud service_ is exactly the same