:relative-path: ../../
include::{docdir}/variables.adoc[]

First of all, if you want to include some services (custom or not), you need to use the _dependency injection_ of ZetaPush. This will ease the injection of your dependencies.

You need to import the package `@zetapush/platform` in order to use `Inject()`. This object will resolve the dependency injection of _cloud services_ and _custom cloud services_.

.Install @zetapush/platform
[source, console, linenums]
----
$ npm install --save @zetapush/platform
----

NOTE: The dependency injection of ZetaPush uses Angular https://github.com/mgechev/injection-js[injection-js^] library.

For example, to import an other service, you simply need to write:

.Import service
[source,typescript,linenums,role="highlight-lines:6"]
----
import { Injectable, Stack } = require('@zetapush/platform'); <1>
import { MyOtherService } from './services'; <2>

@Injectable()
class MyOwnService {
    constructor(private myOtherService: MyOtherService, private stack: Stack) { <3>
        ...
    }
}
----
<1> We import the `Inject` object and a service (_Stack_) provided by ZetaPush
<2> We import an other custom cloud service
<3> We use instances of our injected services in our service throught the constructor

If you import a _custom cloud service_ or a _cloud service_ provided by ZetaPush, you use both similarily
