:relative-path: ../../
include::{docdir}/variables.adoc[]

First of all, if you want to include some services (custom or not), you need to use the _dependency injection_ of ZetaPush. This will ease the injection of your dependencies.

You need to import the package `@zetapush/platform` in order to use `Inject()`. This object will resolve the dependency injection of _cloud services_ and _custom cloud services_.

.Install @zetapush/platform
[source, console, linenums]
----
$ npm install --save @zetapush/platform
----

NOTE: The dependency injection of ZetaPush uses Angular https://github.com/mgechev/injection-js[injection-js^] library.

For example, to import an other service, you simply need to write :

.Import service
[source, javascript, linenums, role="highlight-lines:6-11,13"]
----
const { Inject, Stack } = require('@zetapush/platform'); <1>
const MyOtherService = require('./services.js'); <2>

class MyOwnService {

    static get parameters() { <3>
        return [
            new Inject(MyOtherService),
            new Inject(Stack)
        ]
    }

    constructor(myOtherService, stack) { <4>
        ...
    }
}
----
<1> We import the `Inject` object and a service (_Stack_) provided by ZetaPush
<2> We import an other custom cloud service
<3> We create a static method to implement our dependency injection (_injection-js_ syntax)
<4> We use instances of our injected services in our service throught the constructor

WARNING: The order in your `parameters` method need to be the same in your constructor. (Here, first _MyOtherService_, then _Stack_)

If you import a _custom cloud service_ or a _cloud service_ provided by ZetaPush, you use both similarily
