:relative-path: ../../
include::{docdir}/variables.adoc[]

When you create a _custom cloud service_ that you want to expose to the client, you need to declare it. You have 2 cases:

* Only one _custom cloud service_ exposed
* Many _custom cloud services_ exposed 

NOTE: The `package.json` has a property named `main`. It defines the file where the _custom cloud services_ are exposed. The following examples define them in `worker/index.js`.


== Namespace

When you call a _cloud function_ from a _custom cloud service_, you can specify a _namespace_ (if you have 2 _cloud functions_ on 2 differents _custom cloud services_). 

NOTE: The _namespace_ is never used inside the _custom cloud service_. The _namespace_ is defined when you expose your _custom cloud service_.

For example we have this service:

[source, javascript, linenums]
----
class Api {
    constructor() {}

    hello(name, context) { <1>
        return `Hello ${name} called by ${context.owner}.`;
    }
}

module.exports = {
    api: Api <2>
}
----
<1> The _namespace_ is never passed here
<2> We export this _custom cloud service_ with the namespace 'api'

You can call `hello()` like this:

[source, javascript, linenums]
----
// api is an instance of Api
this.api.hello('Toto', 'api'); <1>
----
We use the method `hello()` from the namespace _api_.

== Only one custom cloud service exposed

In this example, we have 2 _custom cloud services_: One is private and the second is exposed:

include::{docdir}/common/code/expose-one-custom-cloud-service.adoc[leveloffset=+1]

== Many custom cloud services exposed

In this example, we want to expose 2 _custom cloud services_. In this case, we need to specify the namespace of each _custom cloud service_:

include::{docdir}/common/code/expose-many-custom-cloud-services.adoc[leveloffset=+1]
