:relative-path: ../../
include::{docdir}/variables.adoc[]

In this chapter we will see how to consume our _cloud functions_ from a web page.
At the end of this example, we will have one button to call `helloWorld` _cloud function_ and
one section with a message, a number of repetitions and a button to call `saySomething` _cloud function_.

.Mobile applications
[NOTE]
====
Here we show how to create a web page that consumes our _custom cloud service_.

You can also create a mobile application for Android, iOS and Windows Phone as well
as code for a device. You can use any language you want for the client part.

By default we target web because it is currently the most used technology (even to build
some mobile applications using hybrid technologies).
====

As a reminder, here is the code of _custom cloud service_ named `HelloWorldAsCustomCloudService`:

.worker/index.ts
[source,typescript,linenumbers]
----
export default class HelloWorldAsCustomCloudService {                     
    constructor() {}

    helloWorld() {
        return "Hello World";
    }

    saySomething(message: string, times: number) {
        let fullMessage = '';
        for(let i=0 ; i<times ; i++) {
            fullMessage += `${message}\n`
        }
        return fullMessage
    }
}
----

== Prepare your front for using ZetaPush client

By convention the directory structure of a ZetaPush application is defined below. You place
the code of your web page in the `front` directory:

.Tree structure convention
[source, console, subs="attributes,quotes"]
----
{appName}
├── _.zetarc_
├── _.gitignore_
├── *front*
│   ├── ...
│   ├── *index.js*
│   └── *index.html*
├── _worker_
│   ├── ...
│   ├── ...
│   └── index.ts
├── _package.json_
├── _README.md_
└── _tsconfig.json_
----

.Other front files
[TIP]
====
For this example, we only need an HTML page and a JavaScript file. Needless to say that you can
have CSS files, images and anything you want too.

See more information about <<reference.adoc#different_directory_structures, directory structure convention and how to adapt the structure>>.

Moreover, you are not limited to write pure JavaScript code. You can also use any framework you want:

* <<reference.adoc#develop_with_angular, Angular>>
* <<reference.adoc#develop_with_react, React>>
* <<reference.adoc#develop_with_vue, Vue.js>>
* ...

====

For the example, we create an HTML page with a button to display the _HelloWorld_ message in the page each time
the button is clicked:

.front/index.html
[source, html, linenumbers]
----
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Celtia</title>
</head>

<body>
    <button onclick="hello()">hello</button>                    <!--1-->
    <ul id="result-container"></ul>                             <!--2-->

    <script src="https://unpkg.com/@zetapush/client"></script>  <!--2-->
    <script src="./index.js"></script>                          <!--3-->
</body>

</html>
----
<1> We call `hello()` function that is defined later in `index.js`
<2> Define a node that will display received messages
<3> We include the `client` module provided by ZetaPush
<4> We include a JavaScript file to distinguish HTML code from JavaScript code. All could be written in the HTML


Then, in order to interact with ZetaPush cloud, we need to create a client instance
and to connect to the cloud:

.front/index.js
[source, javascript, linenumbers]
----
// Create new ZetaPush Client
const client = new ZetaPushClient.WeakClient();     // <1>
// Create a proxy to invoked worker methods
const api = client.createProxyTaskService();        // <2>
// Handle connection
client.connect()                                    // <3>
  .then(() => {                                     // <4>
    console.debug('onConnectionEstablished');
    [...document.querySelectorAll('button')].forEach((node) =>
      node.removeAttribute('disabled'));
  });
----
<1> Use ZetaPushClient factory to instantiate a client. In this example, we ask for an anonymous connection (it means that actions are not bound to a particular user of your application)
<2> Custom cloud service provides some functions that can be called from a client. For example, the _custom cloud service_ exposes `helloWorld` and `saySomething` _cloud functions_. 
Instead of having to write the signature of these functions in the client too, we simply use a JavaScript link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy[Proxy].
Therefore, you can directly interact with your custom cloud service without writing any pass-through code on the client side.
<3> The client is ready, now connects it to the ZetaPush cloud.
<4> Once the connection is established, the Promise is resolved and you can write some code in `then` callback.

.Available client types
[TIP]
====
`ZetaPushClient` provides several factories to get instances of a client according to
what you want to do. Here we are using a `WeakClient` instance but there are other
<<reference.adoc#client_types, client types>>. 
====


== Call `hello` _cloud function_

Our client is ready and now we want to call _cloud function_ named `helloWorld`, we add the following code:

.front/index.js
[source, javascript, linenumbers, role="highlight-lines:13-16"]
----
// Create new ZetaPush Client
const client = new ZetaPushClient.WeakClient();
// Create a proxy to invoked worker methods
const api = client.createProxyTaskService();
// Handle connection
client.connect()
  .then(() => {
    console.debug('onConnectionEstablished');
    [...document.querySelectorAll('button')].forEach((node) =>
      node.removeAttribute('disabled'));
  });
// Handle DOM events
async function hello() {                                                                                // <1>
  const messageFromCloudFunction = await api.helloWorld();                                        // <2>
  document.getElementById('result-container').innerHTML += `<li>${messageFromCloudFunction}</li>` // <3>
}
----
<1> Each time a user clicks on the button defined in the HTML, this method is called.
<2> Calls the `helloWorld` _cloud function_ and store the result in a variable.
<3> Add a new list item in the HTML page


Before running this sample, we improve our front in order to also understand
how to call a _cloud function_ that has parameters.

== Call `saySomething` _cloud function_

We add two inputs to be able to send values to the `saySomething` _cloud function_.
The first input is a text to repeat. The second input is the number of times to repeat the message.
Here is the updated code:

.front/index.html
[source, html, linenumbers, role="highlight-lines:12-16"]
----
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Celtia</title>
</head>

<body>
    <button onclick="hello()">hello</button>
    <div style="border: 1px solid #ccc">
      Message: <input type="text" id="message-input" />             <!--1-->
      Repeat: <input type="text" value="1" id="repeat-input" />     <!--2-->
      <button onclick="saySeveralTimes()">say something</button>    <!--3-->
    </div>
    <ul id="result-container"></ul>

    <script src="https://unpkg.com/@zetapush/client"></script>
    <script src="./index.js"></script>
</body>

</html>
----
<1> The first input to enter a message
<2> The second input to enter the number of times to repeat the message
<3> A new button to call `saySeveralTimes()` function defined in `index.js`


.front/index.js
[source, javascript, linenumbers, role="highlight-lines:16-22"]
----
// Create new ZetaPush Client
const client = new ZetaPushClient.WeakClient();
// Create a proxy to invoked worker methods
const api = client.createProxyTaskService();
// Handle connection
client.connect()
  .then(() => {
    console.debug('onConnectionEstablished');
    [...document.querySelectorAll('button')].forEach((node) =>
      node.removeAttribute('disabled'));
  });
// Handle DOM events
async function hello() {
  const messageFromCloudFunction = await api.helloWorld();
  document.getElementById('result-container').innerHTML += `<li>${messageFromCloudFunction}</li>`
}
async function saySeveralTimes() {                                                      // <1>
  const message = document.getElementById('message-input').value;                 // <2>
  const repeat = document.getElementById('repeat-input').value;                   // <3>
  const messages = await api.saySomething(message, parseInt(repeat));             // <4>
  document.getElementById('result-container').innerHTML += `<li>${messages}</li>` // <5>
}
----
<1> Each time a user clicks on the button 'say something' defined in the HTML, this method is called.
<2> Reads the value of the input for getting the message.
<3> Reads the value of the input for getting the number of times to display the message.
<4> Calls `saySomething` _cloud function_ with parameters. Note that as second parameter is a number, we have to convert the string from
the input to a number using `parseInt`.
<5> Add a new list item in the HTML page containing the repeated messages

Now everything is ready to run our application.
