:relative-path: ../
include::{docdir}/variables.adoc[]

Now, you will create the business logic of your application. To do this, you will use a _custom cloud service_.

NOTE: A _custom cloud service_ is a class where you develop a business logic. You can create several _custom cloud services_ inside one application. Each _custom cloud service_ can use the _cloud services_ provided by ZetaPush.

In your existing application you already have a _custom cloud service_ on the file `worker/index.ts` (Defined in the `package.json` with the property `main`).

TIP: When you create one or many _custom cloud services_, you need to export them (to use them from the front side). The exportation need to be done in a file of your application, defined in the `package.json`. The property `main` defines this file.

You can fill this file (`worker/index.ts`) with the following content :

== Import _cloud services_ and define constants

First, you need to import the _cloud services_ provided by ZetaPush, used in this application : 

* _Stack_ (Save data in a stack)
* _Messaging_ (Send and receive messages)
* _GroupManagement_ (Manage group of users)

You also need to import _Inject_ that is useful for the dependencies injection.

.Imports and constants
[source,typescript,linenums]
----
import { Stack, Messaging, GroupManagement, Injectable } from '@zetapush/platform';

const CONVERSATION_ID = 'avengersChat';
const CHANNEL_MESSAGING = 'avengersChannel'; <1>
----
<1> On which channel the users send and listen the messages

== Create the class with its constructor

A _custom cloud service_ is a class, so you need to create it.

.Class and constructor
[source,typescript,linenums]
----
export default class AvengersApi {
  /**
   * Constructor of our API
   */
  constructor(
    private stack: Stack,
    private messaging: Messaging,
    private groups: GroupManagement
  ) { <2>
  }
}
----
<1> Syntax of dependencies injection based on `injection-js`.

NOTE: The dependencies injection of ZetaPush use `injection-js`.

== Create the chat

To create our chat, we use the _GroupManagement cloud service_ provided by ZetaPush. The created group includes all users of the conversation.
So we add a method in our class to create this conversation.

.Create conversation
[source,typescript,linenums]
----
/**
 * Create the conversation of the chat, if doesn't already exists
 */
createConversation() {
  const { exists } = await this.groups.exists({
    group: CONVERSATION_ID 
  });
  if (!exists) {
    await this.groups.createGroup({
      group: CONVERSATION_ID
    });
  }
}
----

== Add user in the conversation

When an user come to the chat, we need to add it to the conversation.
So we create a method in our class to add the current user in the conversation. 

[source,typescript,linenums]
----
/**
* Add the current user in the conversation
*/
addMeToConversation(parameters, context) { <1>
  return this.groups.addUser({
    group: CONVERSATION_ID,
      user: context.owner <2>
  });
}
----
<1> Each _cloud function_ in a _custom cloud function_ takes only one parameter. The second is the context, injected by the SDK
<2> We get the caller (owner) of the _cloud function_ from the context.

== Send a message

No we want to send a message on our chat. To do this, we need to follow 3 steps :

. Get all users in the conversation
. Send the message of all users in the conversation
. Store the message in a stack

[source,typescript,linenums]
----
/**
* Send a message on the chat
* @param {Object} message
*/
sendMessage(message = {}) {
  // Get all users inside the conversation
  const group = await this.groups.groupUsers({
    group: CONVERSATION_ID
  });
  const users = group.users;

  // Send the message to each user in the conversation
  this.messaging.send({
    target: users,
    channel: CHANNEL_MESSAGING,
    data: { message }
  });

  // Store the message in a stack
  await this.stack.push({
    stack: CONVERSATION_ID,
    data: message
  });

  return group;
}
----

TIP: There is no specific method to launch an attack, to do this, we only send a specific message throught `sendMessage`.

== Get all messages

To complete our business logic, we need to have an other method in our class to get all messages (when we enter in the chat).

[source,typescript,linenums]
----
/**
* Get all messages in the conversation
*/
getMessages() {
  const { result } = await this.stack.list({
    stack: CONVERSATION_ID
  });
  return result;
}
----

Now your _custom cloud service_ is ready !