:relative-path: ../
include::{docdir}/variables.adoc[]

Once we have our _custom cloud service_, we need to create the frontend of our application. 

== Launch the worker locally

When we working on the frontend part, we often want to test our interaction with the backend logic.
So with ZetaPush, you can launch your worker locally to test this interaction.
To do this you need to use the _CLI_ and run : `zeta run`.
But in this project, the _CLI_ is imported and a script is created with npm, so you just need to launch :

.Run worker locally
[source,console]
----
// In the root of the application
$ npm run start -- --http-server
----

TIP: If you want to install the _ZetaPush CLI_ you can run `npm install -g @zetapush/cli`.

Then you have access to your application on `http://localhost:3000`.

== Interaction with worker

Now you just need to add the interaction with the _custom cloud service_. To do this, fill the file `front/index.js` :

.Interaction with worker
[source,javascript,linenums]
----
import AvengersController from './utils/controller.js'; <1>

// Create the ZetaPush Client
const client = new ZetaPush.WeakClient();
/**
 * Create service to listen incoming messages
 */
const service = client.createService({
  Type: ZetaPushPlatform.Messaging,
  listener: {
    // Listen incoming messages from the channel 'avengersChannel'
    avengersChannel: ({ data }) => controller.onAvengersMessage(data), <2>
  },
});

const controller = new AvengersController(client);

(async function main() {
  // Expose to template
  window.$controller = controller;
  // Connect to ZetaPush
  await client.connect();
  // Notify client connected
  controller.onConnectionEstablished();
})();
----
<1> Import the frontend logic (in the controller)
<2> Cloud service provided by ZetaPush to listen incoming messages
