:relative-path: ../../../
include::{docdir}/variables.adoc[]

In this part we will explain how to use the **Standard User Workflow** in the default behavior, i.e. using the default implementations of each parts of the workflow (For example, the default implementation to send the confirmation email use the _Mailjet_ API).

To use the Standard User Workflow, you just need 4 steps :

* Create a ZetaPush application as usual
* Import and use the Standard User Workflow in your worker
* Configure some properties
* Develop your front by calling the Standard User Workflow API

== Create a ZetaPush application as usual

In this Quickstart, we begin with a generated application using the CLI. So you can run:

[source, console]
----
$ npm init @zetapush myApp
----

We import the library @zetapush/user-management that provides the Standard User Workflow using NPM:

[source, console]
----
$ npm install --save @zetapush/user-management
----

== Import and use the Standard User Workflow in your worker

Your worker contains just this code :

.worker/index.ts
[source,typescript,linenums]
----
import { Module } from '@zetapush/core';
import { StandardUserManagementModule, StandardUserWorkflow, ConfirmationUrlHttpHandler } from '@zetapush/user-management';

@Module({ <1>
  imports: [StandardUserManagementModule], <2>
  expose: {
    user: StandardUserWorkflow, <3>
    http: ConfirmationUrlHttpHandler <4>
  }
})
export default class Api {}
----
<1> As usual, the worker code exports a class (maned _Api_ here). As we import another module (@zetapush/user-management) we need to use @module annotation.
<2> First you need to export a class (named _Api_ here) that is a module (configured with the _@Module()_ annotation). You import the **StandardUserManagementModule** to use it into your application.
<3> The @zetapush/user-management library/cloud service provides the StandardUserWorkflow class. The front needs to call methods of the StandardUserWorkflow class that's why StandardUserWorkflow class is exposed. In this example, the StandardUserWorflow methods are exposed in user namespace.
<4> We also expose _ConfirmationUrlHttpHandler_ to instanciate a web server in your worker that will listen the account confirmation event (When the user clicks on the link in the email).

That all for the worker !

== Configure some properties

Some configuration properties are required (like Mailjet API keys for example) to make the whole workflow work. To configure those properties, you need to create a file named application.json at the root of your application:

.application.json
[source,json,linenums]
----
{
  "email": {
    "from": "celtia@zetapush.com" <1>
  },
  "registration": {
    "confirmation": {
      "base-url": "http://localhost:2999", <2>
      "email": {
        "subject": "Please confirm your account registration"
      },
      "success-url": "http://localhost:3000#login", <3>
      "failure-url": "http://localhost:3000#confirmation-failed" <4>
    }
  },
  "mailjet": {  <5>
    "apikey-public": "", 
    "apikey-private": ""
  }
}
----
<1> We configure the email sender
<2> the `base-url` property is necessary to run the application in local. This property will soon be optional.
<3> Link of your application where the user will be redirected when he confirms his account.
<4> Link of your application where the user will be redirected when the confirmation failed.
<5> Your Mailjet properties.


== Develop your front by calling the Standard User Workflow API

Finally, we just need to call the cloud functions to create a user account, log in and log out from the client part.
You can replace the `front/index.js` file by the following content :

.front/index.js
[source, javascript, linenums]
----
// Create the ZetaPush API
const client = new ZetaPushClient.SmartClient();
const userApi = client.createProxyTaskService({ <1>
  namespace: 'user'
});

// The user is hard-coded because we only show the front -> worker interaction
const user = {
  login: 'test',
  password: 'password',
  email: 'test-zetapush@yopmail.com'
};

async function signUpUser() { <2>
  // First connection as anonymous user to allow us to create a user
  await client.connect();

  // Creation of the user account
  try {
    await userApi.signup({
      credentials: {
        login: user.login,
        password: user.password
      },
      profile: {
        email: user.email
      }
    });
    console.log('User account created');
  } catch (err) {
    console.error('Failed to create user account : ', err);
  }
}

/**
 * Connection of a user
 */
async function connectUser() { <3>
  await client.setCredentials({ login: user.login, password: user.password });
  client
    .connect()
    .then(() => {
      console.log('User connected');
    })
    .catch(err => {
      console.error('Failed to connect user : ', err);
    });
}

/**
 * Disconnection of a user
 */
async function disconnectUser() { <4>
  await client.disconnect();
  console.log('User disconnected');
}
----
<1> We created a ZetaPush client and his API to call our cloud functions (We use the namespace 'user' to call the **Standard User Workflow**).
<2> Function to create an account of the ZetaPush platform for this application.
<3> Function to connect a user.
<4> Function to disconnect a user.

Here is a very basic HTML page to see the result in the console :

.front/index.html
[source, html, linenums]
----
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Standard User Workflow</title>
</head>

<body>
  <button onclick="signUpUser()">Sign up</button>
  <button onclick="connectUser()">Connect</button>

  <script src="https://unpkg.com/@zetapush/client"></script>
  <script src="./index.js"></script>
</body>

</html>
----

Run the following command to run your application in local and serve the front part :

.Run the application
[source, console]
----
$ npm run start -- --serve-front
----

NOTE: For a more real-world sample with a complete UI (signup form and login form) you can go to https://github.com/zetapush/zetapush-examples/tree/master/standard-user-workflow[GitHub ZetaPush Examples].

You can now learn link:#configuration-of-standard-user-workflow[how to deeply configure the Standard User Workflow] or learn link:#extension-of-standard-user-workflow[how to extend this cloud service].
