
== System requirements

To create an application with ZetaPush you only need the NodeJS ecosystem: 

[NOTE]
====
- NodeJS version 8.11.2 (LTS) or higher
- Npm version 5.x or higher
====

NodeJS is used for ZetaPush to:
[NOTE]
====
- create custom cloud services
- locally run custom cloud services
- deploy your application on ZetaPush
====

*Install NodeJS and npm*

Go to https://nodejs.org/en/download/[NodeJS Downloads^] and follow installation instructions.

You also need to install additionnal tools for NodeJS:

[role=tab-container]
Additional tools

[role=tab]
Windows

You must install development tools on Windows (Visual Studio Build Tools and Python). 
Hopefully, there is a npm tool that helps you to install all required dependencies.
You must run this command line using **PowerShell** as **Administrator**:

[source, console]
----
npm install --global --production windows-build-tools
----
Be patient! It may take a while.

[role=tab]
Debian/Ubuntu

Install build tools:

[source, console]
----
sudo apt-get install -y build-essential
----

[role=tab]
Enterprise Linux and Fedora

Install build tools:

[source, console]
----
sudo yum install gcc-c++ make
# or: sudo yum groupinstall 'Development Tools'
----

[role=tab-container-end]
-
