:relative-path: ../../
include::{docdir}/variables.adoc[]

== GdaFilterRequest

=== Properties



.columns: GdaColumnSpec[];
Optional column/cell specifications of the columns/cells to retrieve


.function: Object;
Boolean predicate. The function must accept one parameter : the current row. The return value must be a boolean. When true, the row is retained, otherwise it is filtered out.


.owner: string;
Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user


.page: Pagination;
Pagination information


.requestId: string;
User field for traceability of requests. Synchronous SDK APIs use this field for you.


.start: string;
Start row key (inclusive)


.stop: string;
Stop row key (exclusive)


.table: string;
Table name


=== Source

[source,typescript,linenums]
----
interface GdaFilterRequest {

  /**
   * Optional column/cell specifications of the columns/cells to retrieve
   */
  columns: GdaColumnSpec[];

  /**
   * Boolean predicate. The function must accept one parameter : the current row. The return value must be a boolean. When true, the row is retained, otherwise it is filtered out.
   */
  function: Object;

  /**
   * Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user
   */
  owner: string;

  /**
   * Pagination information
   */
  page: Pagination;

  /**
   * User field for traceability of requests. Synchronous SDK APIs use this field for you.
   */
  requestId: string;

  /**
   * Start row key (inclusive)
   */
  start: string;

  /**
   * Stop row key (exclusive)
   */
  stop: string;

  /**
   * Table name
   */
  table: string;

}
----
