:relative-path: ../../
include::{docdir}/variables.adoc[]

== LogRequest

=== Properties



.contextId: string;
Context ID. Clients and developers must not pass this explicitly. This value was generated by the server and passed back by the worker SDKs.


.custom: Map<string,Object>;
For developer-defined values, tags, etc... A typical usage is to trace an application-generated transaction ID across several API calls, to be able to retrace a full click-stream afterwards


.data: Object;
The actual data you are logging. Can be a text message, or more structured data.


.level: LogLevel;
By setting the level you ensure that this request ends up in the logs only when configured to do so.


.logger: string;
Logger name. Hierarchical, dot-separated identifier, such as 'myClass.myVerb' to ease log storage and filtering.


.owner: string;
Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user


.resource: string;
Refines the identification of a connected client. Automtically set by the server.


.timestampOverride: long;
User supplied timestamp. The server will still store its own timestamp.


=== Source

[source,typescript,linenums]
----
interface LogRequest {

  /**
   * Context ID. Clients and developers must not pass this explicitly. This value was generated by the server and passed back by the worker SDKs.
   */
  contextId: string;

  /**
   * For developer-defined values, tags, etc... A typical usage is to trace an application-generated transaction ID across several API calls, to be able to retrace a full click-stream afterwards
   */
  custom: Map<string,Object>;

  /**
   * The actual data you are logging. Can be a text message, or more structured data.
   */
  data: Object;

  /**
   * By setting the level you ensure that this request ends up in the logs only when configured to do so.
   */
  level: LogLevel;

  /**
   * Logger name. Hierarchical, dot-separated identifier, such as 'myClass.myVerb' to ease log storage and filtering.
   */
  logger: string;

  /**
   * Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user
   */
  owner: string;

  /**
   * Refines the identification of a connected client. Automtically set by the server.
   */
  resource: string;

  /**
   * User supplied timestamp. The server will still store its own timestamp.
   */
  timestampOverride: long;

}
----
