:relative-path: ../../
include::{docdir}/variables.adoc[]

== TimerRequest

=== Properties



.delay: int;
Delay in seconds before calling the given API. Must be a integer between 1 and 120.


.deploymentId: string;
DeploymentId of the target service.


.loud: boolean;
Specifies whether this call should generate all expected direct user notifications (primary outputs). Does not affect side-effects (other outputs). Defaults to false


.owner: string;
Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user


.parameter: Map<string,Object>;
Parameter that will be passed to the target verb when called. The format is the format accepted by the target.


.requestId: string;
User field for traceability of requests. Synchronous SDK APIs use this field for you.


.verb: string;
Verb to be called within the target service.


=== Source

[source,typescript,linenums]
----
interface TimerRequest {

  /**
   * Delay in seconds before calling the given API. Must be a integer between 1 and 120.
   */
  delay: int;

  /**
   * DeploymentId of the target service.
   */
  deploymentId: string;

  /**
   * Specifies whether this call should generate all expected direct user notifications (primary outputs). Does not affect side-effects (other outputs). Defaults to false
   */
  loud: boolean;

  /**
   * Optional User key. When calling the API, defaults to the current (calling) user's primary key. For impersonation purposes, the caller may use the key of another user, provided that the proper authorizations have been given by the impersonated user
   */
  owner: string;

  /**
   * Parameter that will be passed to the target verb when called. The format is the format accepted by the target.
   */
  parameter: Map<string,Object>;

  /**
   * User field for traceability of requests. Synchronous SDK APIs use this field for you.
   */
  requestId: string;

  /**
   * Verb to be called within the target service.
   */
  verb: string;

}
----
