:relative-path: ../../
include::{docdir}/variables.adoc[]

It is possible to configure the structure of your application.
We list in this part the different possibilities.


[#change-worker-entry-point]
== Entry point for worker

By default, the entry point of your worker code is the file `./worker/index.ts` to follow the NodeJS convention.

You can configure the entry point of the worker setting the `main` property of the `package.json` file.

For example if you want to use the file `./worker/main.ts` as entry point you need to have the following `package.json` content :

.Custom worker entry point
[source, json, linenums]
----
{
  "name": "myApp",
  "version": "0.1.0",
  "main": "worker/main.ts",       // <1>
  // Other properties...
}
----
<1> Path of the file used as entry point

[#different_directory_structures]
== Custom directory structure

[TODO]
====
This section will be useful if you want to change the structure of your application. 
The most common case is when you want to use framework (Angular, React, VueJS for example).
This documentation will be soon ready.
====

== Script alias

[NOTE]
====
Npm provides a handy feature
to run scripts provided by dependencies without needing to change your computer settings or
install the tool. ZetaPush defines npm https://medium.com/@mxstbr/npm-scripts-explained-f125e85eb378[script aliases^]
to run the ZetaPush _CLI_ through npm.

See <<developer-manual.adoc#_using_cli, for more information about the ways of using the CLI>>.
====



