:relative-path: ../../
include::{docdir}/variables.adoc[]

Some properties are available in the `application.json` file to configure the _Standard User Workflow_. We will list all of them in this section:

== Organization

[#configure_organization_name]
.Organization name

Name of your organization. It is used in the default email sender (`noreply@${organizationName}.com`).

[source, json]
----
{
  "organization": {
    "name": "ZetaPush"
  }
}
----

.Optional property
[NOTE]
====
This property is optional. If it is not configured, you need to <<reference#configure_email_sender, configure an email sender>>.
====

== Email

[#configure_email_sender]
.Email sender

Let you configure the sender of the different emails used in your application. For example for account registration.

.Default email sender
[NOTE]
====
The default email sender is `noreply@${organizationName}.com`.
So If this property is not set, you need to configure the <<reference#configure_organization_name, organization name>>.
====

This property support the standard notation for email (name <email@domain.com>):

[source, json]
----
{
  "email": {
    "sender": "Sender Name <sender@my-domain.com>"  // <1>
  }
}
----
<1> You can also only type the email (ex: "sender@my-domain.com")

== Account registration

=== Account confirmation

During the account creation workflow of the _StandardUserWorkflow_, an email is sent to ask the end-user to confirm his email. You can configure many properties about this.

.Email subject

You can set the email subject of the confirmation account creation like below:

[source, json]
----
{
  "registration": {
    "confirmation": {
      "email": {
        "subject": "Please confirm your account registration"
      }
    }
  }
}
----

.Mandatory property
[NOTE]
====
This property is mandatory.
====

.URL Redirection

When an end-user validate his account, he is redirected to a specific URL of your application. There are 2 cases, if the confirmation is OK or if it failed:

[source, json]
----
{
  "registration": {
    "confirmation": {
      "success-url": "https://my-app-url/#login",                   // <1>
      "failure-url": "https://my-app-url/#confirmation-failed"      // <2>
    }
  }
}
----
<1> The end-user is redirected to this URL when the confirmation is OK
<2> The end-user is redirected to this URL when the confirmation failed


You can also only set the path of your urls. The base url will be automatically provided by ZetaPush:

[source, json]
----
{
  "registration": {
    "confirmation": {
      "success-url": "#login",
      "failure-url": "#confirmation-failed"
    }
  }
}
----

.Mandatory property
[NOTE]
====
This property is mandatory.
====


== Reset password workflow

.URL to ask to change password

It is possible to configure the path of your application where the end-user will be able to choose his new password. 

[source, json]
----
{
  "reset-password": {
    "ask": {
      "url": "http://localhost:3000/reset-password#${token}",     // <1>
    }
  }
}
----
<1> The token is sent through the URL. To use it you need to put `${token}` in your URL.

You can also only set the path of your url. The base url will be automatically provided by ZetaPush:

[source, json]
----
{
  "reset-password": {
    "ask": {
      "url": "/reset-password#${token}",     // <1>
    }
  }
}
----

.Mandatory property
[NOTE]
====
This property is mandatory.
====


.Email subject

You can configure the subject of the sent email to reset the password:

[source, json]
----
{
  "reset-password": {
    "ask": {
      "email": {
        "subject": "Please choose a new password"
      }
    }
  }
}
----

.Mandatory property
[NOTE]
====
This property is mandatory.
====


== Email provider configuration

To use the _StandardUserWorkflow_ you need to configure an email provider.
Today, you can use two possibilities: _Mailjet_ or _SMTP_.

.Mandatory property
[NOTE]
====
You need to set at least one email provider configuration and you need to have only one email provider configuration enabled.
====


=== Mailjet configuration

To use the _Mailjet_ configuration you need to configure the `application.json` file like this:

[source, json]
----
{
  "mailjet": {
    "apikey-public": "my-mailjet-apikey-public",
    "apikey-private": "my-mailjet-apikey-private",
    "enable": "true",                                 // <1>
    "url": "https://api.mailjet.com/v3.1/send"        // <2>
  }
}
----
<1> Optional property to define that we use this email provider configuration. (The default value is `true`)
<2> Define the URL to use for your _Mailjet_ email provider. By default the used URL is `https://api.mailjet.com/v3.1/send`.

=== SMTP configuration

To use the _SMTP_ configuration you need to configure the `application.json` file like this:

[source, json]
----
{
  "smtp": {
    "host": "my-smtp-host",
    "port": "465",                      // <1>
    "username": "my-smtp-username",
    "password": "my-smtp-password",
    "ssl": true,                        // <2>
    "starttls": true,                   // <2>
    "enable": true                      // <3>
  }
}
----
<1> Default to 465
<2> Default to `true`
<3> Optional property to define that we use this email provider configuration. (The default value is `true`)
